// Coastline line shaders drawn above product layers.
export const coastVS = `#version 300 es
precision highp float; in vec2 a_lonLat,a_other; uniform vec2 u_viewport,u_translate; uniform vec4 u_rotate; uniform int u_projMode; out float v_alpha; const float PI=3.14159265359; const float TAU=6.28318530718;
vec2 pxToClip(vec2 px){return vec2(px.x/u_viewport.x*2.-1.,1.-px.y/u_viewport.y*2.);}
vec2 rotateLL(vec2 ll){float lambda=radians(ll.x+u_rotate.x), phi=radians(ll.y), deltaPhi=radians(u_rotate.y), deltaGamma=radians(u_rotate.z); float cosPhi=cos(phi), x=cos(lambda)*cosPhi, y=sin(lambda)*cosPhi, z=sin(phi); float cd=cos(deltaPhi), sd=sin(deltaPhi), cg=cos(deltaGamma), sg=sin(deltaGamma); float k=z*cd+x*sd; return vec2(atan(y*cg-k*sg,x*cd-z*sd),asin(clamp(k*cg+y*sg,-1.,1.)));}
vec2 project(vec2 ll,out bool ok){vec2 r=rotateLL(ll); float lambda=r.x; float phi=r.y; if(u_projMode==0){float cp=cos(phi),cl=cos(lambda),sl=sin(lambda); float cosc=cp*cl; if(cosc<=0.001){ok=false; return vec2(2.);} ok=true; return pxToClip(vec2(u_translate.x+cp*sl*u_rotate.w,u_translate.y-sin(phi)*u_rotate.w));} lambda=mod(lambda+PI,TAU)-PI; if(u_projMode==1){if(abs(phi)>1.48442223){ok=false; return vec2(2.);} float y=log(tan(.78539816339+phi*.5)); ok=true; return pxToClip(vec2(u_translate.x+lambda*u_rotate.w,u_translate.y-y*u_rotate.w));} if(u_projMode==3){float p2=phi*phi,p4=p2*p2,p6=p4*p2,p8=p4*p4,p10=p8*p2,p12=p10*p2; float x=lambda*(.8707-.131979*p2-.013791*p4+.003971*p10-.001529*p12); float y=phi*(1.007226+.015085*p2-.044475*p6+.028874*p8-.005916*p10); ok=true; return pxToClip(vec2(u_translate.x+x*u_rotate.w,u_translate.y-y*u_rotate.w));} ok=true; return pxToClip(vec2(u_translate.x+lambda*u_rotate.w,u_translate.y-phi*u_rotate.w));}
void main(){bool ok=false, okOther=false; vec2 clip=project(a_lonLat,ok); vec2 other=project(a_other,okOther); vec2 d=clip-other; float jump=length(d); float limit=(u_projMode==0)?1.2:.08; bool valid=ok&&okOther&&jump<limit&&abs(d.x)<limit&&abs(d.y)<limit; gl_Position=valid?vec4(clip,0.,1.):vec4(2.,2.,1.,1.); v_alpha=valid?1.:0.;}`;

export const coastFS = `#version 300 es
precision highp float; uniform float u_alpha; in float v_alpha; out vec4 outColor; void main(){if(v_alpha<=0.) discard; outColor=vec4(.92,.94,.94,u_alpha);}`;
