// Scalar overlay shader. Reprojects screen pixels back to lon/lat and samples data.
export const overlayFS = `#version 300 es
precision highp float; precision highp sampler2D; in vec2 v_uv; uniform sampler2D u_data,u_ramp; uniform vec2 u_dataSize,u_viewport,u_translate,u_center; uniform vec4 u_rotate,u_grid,u_gridFlags; uniform vec2 u_range; uniform float u_alpha; uniform int u_projMode,u_enabled; out vec4 outColor; const float PI=3.14159265359; const float TAU=6.28318530718;
float wrap180(float x){x=mod(x+180.,360.); if(x<0.)x+=360.; return x-180.;}
vec2 inverseRotate(vec3 p){float deltaPhi=radians(u_rotate.y), deltaGamma=radians(u_rotate.z); float cd=cos(deltaPhi), sd=sin(deltaPhi), cg=cos(deltaGamma), sg=sin(deltaGamma); vec3 q; q.x=p.x; q.y=p.y*cg+p.z*sg; q.z=p.z*cg-p.y*sg; vec3 r; r.x=q.x*cd+q.z*sd; r.y=q.y; r.z=q.z*cd-q.x*sd; return vec2(wrap180(degrees(atan(r.y,r.x))-u_rotate.x),degrees(asin(clamp(r.z,-1.,1.))));}
float mercY(float phi){return log(tan(.78539816339+phi*.5));}
bool invertProject(vec2 px,out vec2 ll){float scale=u_rotate.w; vec2 q=vec2((px.x-u_translate.x)/scale,-(px.y-u_translate.y)/scale); vec3 p; if(u_projMode==0){float rr=dot(q,q); if(rr>1.)return false; p=vec3(sqrt(max(0.,1.-rr)),q.x,q.y);} else {if(abs(q.x)>PI)return false; float centerLambda=radians(u_center.x), centerPhi=radians(u_center.y); float lambda=q.x+centerLambda; float phi=q.y+centerPhi; if(u_projMode==1){float safeCenterPhi=clamp(centerPhi,-1.48442223,1.48442223); phi=2.*atan(exp(q.y+mercY(safeCenterPhi)))-PI*.5; if(abs(phi)>1.48442223)return false;} else if(abs(phi)>PI*.5){return false;} p=vec3(cos(phi)*cos(lambda),cos(phi)*sin(lambda),sin(phi));} ll=inverseRotate(p); return true;}
float sampleData(vec2 lonLat){float lon=lonLat.x; float lat=clamp(lonLat.y,u_grid.z,u_grid.w); float nx=max(1.,u_dataSize.x), ny=max(1.,u_dataSize.y); float x; if(u_gridFlags.z>.5){float base=(u_gridFlags.y>.5)?u_grid.x:-180.; float dx=mod((lon-base)+360.,360.); x=dx/360.*nx;}else{x=clamp((lon-u_grid.x)/max(1e-6,u_grid.y-u_grid.x),0.,1.)*(nx-1.);} float y=(lat-u_grid.z)/max(1e-6,u_grid.w-u_grid.z)*(ny-1.); if(u_gridFlags.x>.5)y=(ny-1.)-y; y=clamp(y,0.,ny-1.); int x0=int(floor(x)), y0=int(floor(y)); float tx=fract(x), ty=fract(y); int x1=x0+1, y1=min(y0+1,int(ny)-1); if(u_gridFlags.z>.5){int nxi=int(nx); x0=int(mod(float(x0+nxi),float(nxi))); x1=int(mod(float(x1+nxi),float(nxi)));}else{x0=clamp(x0,0,int(nx)-1); x1=clamp(x1,0,int(nx)-1);} float v00=texelFetch(u_data,ivec2(x0,y0),0).r; float v10=texelFetch(u_data,ivec2(x1,y0),0).r; float v01=texelFetch(u_data,ivec2(x0,y1),0).r; float v11=texelFetch(u_data,ivec2(x1,y1),0).r; return mix(mix(v00,v10,tx),mix(v01,v11,tx),ty);}
void main(){if(u_enabled==0){discard;} vec2 px=vec2(gl_FragCoord.x,u_viewport.y-gl_FragCoord.y); vec2 ll; if(!invertProject(px,ll)){discard;} float v=sampleData(ll); if(!(v==v)){discard;} float t=clamp((v-u_range.x)/max(1e-6,u_range.y-u_range.x),0.,1.); vec3 c=texture(u_ramp,vec2(t,.5)).rgb; outColor=vec4(c,u_alpha);}`;
