// Swath/product mesh shaders for geolocated satellite-like rasters.
export const productVS = `#version 300 es
precision highp float; in vec2 a_lonLat,a_uv; uniform vec2 u_viewport,u_translate,u_center; uniform vec4 u_rotate; uniform int u_projMode; uniform float u_lonOffset; out vec2 v_uv; out float v_front; out vec2 v_clipLL; const float PI=3.14159265359; const float TAU=6.28318530718;
vec2 pxToClip(vec2 px){return vec2(px.x/u_viewport.x*2.-1.,1.-px.y/u_viewport.y*2.);}
vec2 rotateLL(vec2 ll){float lambda=radians(ll.x+u_lonOffset+u_rotate.x), phi=radians(ll.y), deltaPhi=radians(u_rotate.y), deltaGamma=radians(u_rotate.z); float cosPhi=cos(phi), x=cos(lambda)*cosPhi, y=sin(lambda)*cosPhi, z=sin(phi); float cd=cos(deltaPhi), sd=sin(deltaPhi), cg=cos(deltaGamma), sg=sin(deltaGamma); float k=z*cd+x*sd; return vec2(atan(y*cg-k*sg,x*cd-z*sd),asin(clamp(k*cg+y*sg,-1.,1.)));}
float mercY(float phi){return log(tan(.78539816339+phi*.5));}
vec2 naturalEarth(vec2 p){float phi=p.y,p2=phi*phi,p4=p2*p2,p6=p4*p2,p8=p4*p4,p10=p8*p2,p12=p10*p2; return vec2(p.x*(.8707-.131979*p2-.013791*p4+.003971*p10-.001529*p12),phi*(1.007226+.015085*p2-.044475*p6+.028874*p8-.005916*p10));}
vec2 project(vec2 ll,out bool ok,out float front,out vec2 clipLL){float lambda; float phi; if(u_projMode==0){vec2 r=rotateLL(ll); lambda=r.x; phi=r.y; clipLL=vec2(lambda,phi); float cp=cos(phi),cl=cos(lambda),sl=sin(lambda); float cosc=cp*cl; float x=cp*sl; float y=sin(phi); front=cosc; ok=true; return pxToClip(vec2(u_translate.x+x*u_rotate.w,u_translate.y-y*u_rotate.w));} lambda=radians(ll.x+u_lonOffset+u_rotate.x); phi=radians(ll.y); float centerLambda=radians(u_center.x), centerPhi=radians(u_center.y); float relLambda=lambda-centerLambda; clipLL=vec2(relLambda,phi); front=1.; ok=true; if(u_projMode==1){float safePhi=clamp(phi,-1.48442223,1.48442223); float safeCenterPhi=clamp(centerPhi,-1.48442223,1.48442223); float y=mercY(safePhi), cy=mercY(safeCenterPhi); return pxToClip(vec2(u_translate.x+relLambda*u_rotate.w,u_translate.y-(y-cy)*u_rotate.w));} if(u_projMode==3){float safePhi=clamp(phi,-PI*.5,PI*.5); vec2 p=naturalEarth(vec2(lambda,safePhi)); vec2 c=naturalEarth(vec2(centerLambda,clamp(centerPhi,-PI*.5,PI*.5))); return pxToClip(vec2(u_translate.x+(p.x-c.x)*u_rotate.w,u_translate.y-(p.y-c.y)*u_rotate.w));} return pxToClip(vec2(u_translate.x+relLambda*u_rotate.w,u_translate.y-(phi-centerPhi)*u_rotate.w));}
void main(){bool ok=false; float front=1.; vec2 clipLL=vec2(0.); vec2 clip=project(a_lonLat,ok,front,clipLL); if(!ok){gl_Position=vec4(2,2,1,1); v_uv=a_uv; v_front=-1.; v_clipLL=clipLL; return;} gl_Position=vec4(clip,0,1); v_uv=a_uv; v_front=front; v_clipLL=clipLL;}`;

export const productFS = `#version 300 es
precision highp float; precision highp sampler2D; uniform sampler2D u_data,u_ramp; uniform vec2 u_dataSize,u_range; in vec2 v_uv; in float v_front; in vec2 v_clipLL; out vec4 outColor; const float PI=3.14159265359;
float valid(float v){return (v==v&&abs(v)<1e20)?1.:0.;}
float clean(float v){return valid(v)>.5?v:0.;}
void main(){if(v_front<=0.001) discard; if(abs(v_clipLL.x)>PI||abs(v_clipLL.y)>PI*.5) discard; vec2 xy=clamp(v_uv,vec2(0.),vec2(1.))*max(vec2(1.),u_dataSize-1.); vec2 p=floor(xy); vec2 f=fract(xy); ivec2 p00=ivec2(p); ivec2 p10=ivec2(min(p+vec2(1.,0.),u_dataSize-1.)); ivec2 p01=ivec2(min(p+vec2(0.,1.),u_dataSize-1.)); ivec2 p11=ivec2(min(p+vec2(1.,1.),u_dataSize-1.)); float v00=texelFetch(u_data,p00,0).r, v10=texelFetch(u_data,p10,0).r, v01=texelFetch(u_data,p01,0).r, v11=texelFetch(u_data,p11,0).r; float w00=(1.-f.x)*(1.-f.y)*valid(v00), w10=f.x*(1.-f.y)*valid(v10), w01=(1.-f.x)*f.y*valid(v01), w11=f.x*f.y*valid(v11); float w=w00+w10+w01+w11; if(w<=0.) discard; float v=(clean(v00)*w00+clean(v10)*w10+clean(v01)*w01+clean(v11)*w11)/w; float t=clamp((v-u_range.x)/max(1e-6,u_range.y-u_range.x),0.,1.); vec3 c=texture(u_ramp,vec2(t,.5)).rgb; outColor=vec4(c,.82);}`;
